In [2]:
import numpy as np

In [27]:
a = np.array([[4,5,1],[2,9,8],[4,2,5]])
b = np.array([[1,3,4],[4,5,6],[7,8,9]])

print(np.dot(a,b))

[[ 31  45  55]
 [ 94 115 134]
 [ 47  62  73]]


In [28]:
print("Array 1 : \n",np.transpose(a))
print("Array 2 : \n",np.transpose(b))

Array 1 : 
 [[4 2 4]
 [5 9 2]
 [1 8 5]]
Array 2 : 
 [[1 4 7]
 [3 5 8]
 [4 6 9]]


In [29]:
print("Trace A : \n",np.trace(a))
print("Trace B : \n",np.trace(b))

Trace A : 
 18
Trace B : 
 15


In [30]:
print("Rank A : \n",np.linalg.matrix_rank(a))
print("Rank B : \n",np.linalg.matrix_rank(b))

Rank A : 
 3
Rank B : 
 3


In [31]:
print("Determinant of A : \n",int(np.linalg.det(a)))
print("Determinant of B : \n",int(np.linalg.det(b)))

Determinant of A : 
 194
Determinant of B : 
 3


In [32]:
print("Inverse of A : \n",np.linalg.inv(a))
print("Inverse of B : \n",np.linalg.inv(b))

Inverse of A : 
 [[ 0.14948454 -0.1185567   0.15979381]
 [ 0.11340206  0.08247423 -0.15463918]
 [-0.16494845  0.06185567  0.13402062]]
Inverse of B : 
 [[-1.          1.66666667 -0.66666667]
 [ 2.         -6.33333333  3.33333333]
 [-1.          4.33333333 -2.33333333]]


In [39]:
print("Eigen value of A : \n",np.linalg.eig(a)[0])
print("Eigen vector of A : \n",np.linalg.eig(a)[1])

Eigen value of A : 
 [13.89507705+0.j          2.05246147+3.12236789j  2.05246147-3.12236789j]
Eigen vector of A : 
 [[-0.44716502+0.j          0.63649912+0.j          0.63649912-0.j        ]
 [-0.80837792+0.j         -0.21416695+0.50125717j -0.21416695-0.50125717j]
 [-0.38284277+0.j         -0.1687718 -0.51890144j -0.1687718 +0.51890144j]]


In [40]:
print("Eigen value of B : \n",np.linalg.eig(b)[0])
print("Eigen vector of B : \n",np.linalg.eig(b)[1])

Eigen value of B : 
 [16.74279079 -1.63307009 -0.1097207 ]
Eigen vector of B : 
 [[-0.30193353 -0.84189509  0.21125621]
 [-0.5133138   0.0198902  -0.80917664]
 [-0.80333374  0.53927455  0.54827363]]
