In [1]:
import numpy as np

In [15]:
arr1 = np.array([1,2])
arr2 = np.array([3,4])

print("Array 1 : ", arr1)
print("Array 2 : ", arr2)

print("Greater : ", np.greater(arr1,arr2))
print("Greater Equal : ", np.greater_equal(arr1,arr2))
print("Equal : ", np.equal(arr1,arr2))
print("Array equal : ", np.array_equal(arr1,arr2))

Array 1 :  [1 2]
Array 2 :  [3 4]
Greater :  [False False]
Greater Equal :  [False False]
Equal :  [False False]
Array equal :  False


In [18]:
new_array = np.arange(30,71,2)
print(new_array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [27]:
id = np.identity(3,dtype=int)
print(id)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [32]:
arr = np.arange(0,21)
arr[9:16] *= -1
print(arr)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [42]:
arr = np.zeros((5,5))
np.fill_diagonal(arr,[1,2,3,4,5,6])
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [54]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr,axis=0))

[12 15 18]


In [58]:
np.savetxt('array.txt',arr)
print(np.loadtxt('array.txt').astype(np.int64))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr = np.random.randint(0,10,size=(3,3))
print(arr)

arr[[0,2]] = arr[[2,0]]
print(arr)

[[4 7 5]
 [8 7 3]
 [7 6 3]]
[[7 6 3]
 [8 7 3]
 [4 7 5]]


In [18]:
a = np.arange(1,6)
b = np.arange(6,11)
print(np.multiply(a,b))

[ 6 14 24 36 50]
